### PR TITLE
Null Safety

### PR DESCRIPTION
**Pull request by bradintheusa**
This has null safety and I made the example into an app that can be run.

### CODE REVIEW

**Comment by pratikbaid3** [comment]
@GusRodrigues86 can you please look into the null safety issue. It would be a great help. Thanks

**Comment by lyngbach** [comment]
Could this PR be looked into? It would be awesome if it could be merged.

**Comment by GusRodrigues86** [comment]
This rep is no longer supported. feel free to fork and publish as your own.

I will be closing this PR and consider this package abandoned and marked to be removed in the future.

**Comment by bradintheusa** [comment]
Any chance you could hand it over? I'd like to keep working on it.

**Comment by GusRodrigues86** [comment]
You already have an repo with the same name as this and is blocking the
transfer

Gustavo Rodrigues

**Pull request closed without merging**
